/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat10
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package manager.org.apache.jsp.WEB_002dINF.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.Enumeration;
import jakarta.servlet.http.HttpSession;
import org.apache.catalina.Session;
import org.apache.catalina.manager.JspHelper;
import org.apache.catalina.util.ContextName;

public final class sessionDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("jakarta.servlet.http.HttpSession");
    _jspx_imports_classes.add("org.apache.catalina.util.ContextName");
    _jspx_imports_classes.add("java.util.Enumeration");
    _jspx_imports_classes.add("org.apache.catalina.manager.JspHelper");
    _jspx_imports_classes.add("org.apache.catalina.Session");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
      out.write("\n\n\n\n\n\n\n<!DOCTYPE html\n     PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\n     \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n");
      out.write("\n\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\">\n");
 String path = (String) request.getAttribute("path");
   String version = (String) request.getAttribute("version");
   ContextName cn = new ContextName(path, version);
   Session currentSession = (Session)request.getAttribute("currentSession");
   String currentSessionId = null;
   HttpSession currentHttpSession = null;
   if (currentSession != null) {
       currentHttpSession = currentSession.getSession();
       currentSessionId = JspHelper.escapeXml(currentSession.getId());
   } else {
       currentSessionId = "Session invalidated";
   }
   String submitUrl = JspHelper.escapeXml(response.encodeURL(
           ((HttpServletRequest) pageContext.getRequest()).getRequestURI() +
           "?path=" + path + "&version=" + version));

      out.write("\n<head>\n    <meta http-equiv=\"content-type\" content=\"text/html; charset=iso-8859-1\"/>\n    <meta http-equiv=\"pragma\" content=\"no-cache\"/><!-- HTTP 1.0 -->\n    <meta http-equiv=\"cache-control\" content=\"no-cache,must-revalidate\"/><!-- HTTP 1.1 -->\n    <meta http-equiv=\"expires\" content=\"0\"/><!-- 0 is an invalid value and should be treated as 'now' -->\n    <meta http-equiv=\"content-language\" content=\"en\"/>\n    <meta name=\"author\" content=\"Cedrik LIME\"/>\n    <meta name=\"copyright\" content=\"copyright 2005-2022 the Apache Software Foundation\"/>\n    <meta name=\"robots\" content=\"noindex,nofollow,noarchive\"/>\n    <title>Sessions Administration: details for ");
      out.print( currentSessionId );
      out.write("</title>\n</head>\n<body>\n");
 if (currentHttpSession == null) { 
      out.write("\n   <h1>");
      out.print(currentSessionId);
      out.write("</h1>\n");
 } else { 
      out.write("\n   <h1>Details for Session ");
      out.print( currentSessionId );
      out.write("</h1>\n\n   <table style=\"text-align: left;\" border=\"0\">\n     <tr>\n       <th>Session Id</th>\n       <td>");
      out.print( currentSessionId );
      out.write("</td>\n     </tr>\n     <tr>\n       <th>Guessed Locale</th>\n       <td>");
      out.print( JspHelper.guessDisplayLocaleFromSession(currentSession) );
      out.write("</td>\n     </tr>\n     <tr>\n       <th>Guessed User</th>\n       <td>");
      out.print( JspHelper.guessDisplayUserFromSession(currentSession) );
      out.write("</td>\n     </tr>\n     <tr>\n       <th>Creation Time</th>\n       <td>");
      out.print( JspHelper.getDisplayCreationTimeForSession(currentSession) );
      out.write("</td>\n     </tr>\n     <tr>\n       <th>Last Accessed Time</th>\n       <td>");
      out.print( JspHelper.getDisplayLastAccessedTimeForSession(currentSession) );
      out.write("</td>\n     </tr>\n     <tr>\n       <th>Session Max Inactive Interval</th>\n       <td>");
      out.print( JspHelper.secondsToTimeString(currentSession.getMaxInactiveInterval()) );
      out.write("</td>\n     </tr>\n     <tr>\n       <th>Used Time</th>\n       <td>");
      out.print( JspHelper.getDisplayUsedTimeForSession(currentSession) );
      out.write("</td>\n     </tr>\n     <tr>\n       <th>Inactive Time</th>\n       <td>");
      out.print( JspHelper.getDisplayInactiveTimeForSession(currentSession) );
      out.write("</td>\n     </tr>\n     <tr>\n       <th>TTL</th>\n       <td>");
      out.print( JspHelper.getDisplayTTLForSession(currentSession) );
      out.write("</td>\n     </tr>\n   </table>\n\n   <form method=\"post\" action=\"");
      out.print( submitUrl );
      out.write("\">\n     <div>\n       <input type=\"hidden\" name=\"sessionId\" value=\"");
      out.print( currentSessionId );
      out.write("\" />\n       <input type=\"hidden\" name=\"action\" value=\"sessionDetail\" />\n       ");

       if ("Primary".equals(request.getParameter("sessionType"))) {
       
      out.write("\n         <input type=\"hidden\" name=\"sessionType\" value=\"Primary\" />\n       ");

       }
       
      out.write("    <input type=\"submit\" value=\"Refresh\" />\n     </div>\n   </form>\n\n   <div class=\"error\">");
      out.print( JspHelper.escapeXml(request.getAttribute("error")) );
      out.write("</div>\n   <div class=\"message\">");
      out.print( JspHelper.escapeXml(request.getAttribute("message")) );
      out.write("</div>\n\n   <table style=\"text-align: left;\" border=\"1\" cellpadding=\"2\" cellspacing=\"2\">\n   ");
 int nAttributes = 0;
      Enumeration<String> attributeNamesEnumeration = currentHttpSession.getAttributeNames();
      while (attributeNamesEnumeration.hasMoreElements()) {
          attributeNamesEnumeration.nextElement();
          ++nAttributes;
      }
   
      out.write("\n       <caption style=\"font-variant: small-caps;\">");
      out.print( JspHelper.formatNumber(nAttributes) );
      out.write(" attributes</caption>\n       <thead>\n           <tr>\n               <th>Remove Attribute</th>\n               <th>Attribute name</th>\n               <th>Attribute value</th>\n           </tr>\n       </thead>\n       ");
      out.write("\n       <tbody>\n   ");
 attributeNamesEnumeration = currentHttpSession.getAttributeNames();
      while (attributeNamesEnumeration.hasMoreElements()) {
          String attributeName = attributeNamesEnumeration.nextElement();
   
      out.write("\n           <tr>\n               <td align=\"center\">\n                   <form method=\"post\" action=\"");
      out.print( submitUrl );
      out.write("\">\n                       <div>\n                           <input type=\"hidden\" name=\"action\" value=\"removeSessionAttribute\" />\n                           <input type=\"hidden\" name=\"sessionId\" value=\"");
      out.print( currentSessionId );
      out.write("\" />\n                           <input type=\"hidden\" name=\"attributeName\" value=\"");
      out.print( JspHelper.escapeXml(attributeName) );
      out.write("\" />\n                           ");

                             if ("Primary".equals(request.getParameter("sessionType"))) {
                           
      out.write("\n                             <input type=\"submit\" value=\"Remove\" />\n                             <input type=\"hidden\" name=\"sessionType\" value=\"Primary\" />\n                           ");

                             } else {
                               out.print("Primary sessions only");
                             }
                           
      out.write("\n                       </div>\n                   </form>\n               </td>\n               <td>");
      out.print( JspHelper.escapeXml(attributeName) );
      out.write("</td>\n               <td>");
 Object attributeValue = currentHttpSession.getAttribute(attributeName); 
      out.write("<span title=\"");
      out.print( attributeValue == null ? "" : attributeValue.getClass().toString() );
      out.write('"');
      out.write('>');
      out.print( JspHelper.escapeXml(attributeValue) );
      out.write("</span></td>\n           </tr>\n   ");
 } // end while 
      out.write("\n       </tbody>\n   </table>\n");
 } // endif
      out.write("\n\n<form method=\"post\" action=\"");
      out.print(submitUrl);
      out.write("\">\n  <p style=\"text-align: center;\">\n    <input type=\"submit\" value=\"Return to session list\" />\n  </p>\n</form>\n\n");
      out.write("\n\n</body>\n</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
